[pytest]
base_url = https://the-internet.herokuapp.com
addopts = -v --html=reports/report.html --self-contained-html
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO

log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

markers =
    smoke: smoke tests
    regression: regression tests
    api: API tests
    ui: UI tests
    network: Network reliability tests
    ai_generated: Tests created by the AI test generator