const METRICS = [
  { value: "8", label: "tests generated" },
  { value: "9.47s", label: "total execution" },
  { value: "100%", label: "pass rate" },
  { value: "1", label: "sentence input" },
];

const TEST_RESULTS = [
  { name: "test_login_succeeds_with_valid_credentials", time: "1.21s" },
  { name: "test_login_fails_with_wrong_password", time: "1.03s" },
  { name: "test_login_fails_with_empty_username", time: "0.98s" },
  { name: "test_login_fails_with_empty_password", time: "1.11s" },
  { name: "test_login_fails_with_sql_injection_attempt", time: "1.44s" },
  { name: "test_login_redirects_to_secure_area_on_success", time: "1.32s" },
  { name: "test_login_page_title_updates_after_auth", time: "1.19s" },
  { name: "test_login_error_message_visible_on_failure", time: "1.19s" },
];

export default function CaseStudy() {
  return (
    <section id="case-study" className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-zinc-950 via-indigo-950/[0.06] to-zinc-950 pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <p className="text-indigo-400 text-sm font-semibold uppercase tracking-widest mb-3">
            Real Results
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            8 tests in{" "}
            <span className="gradient-text">9.47 seconds</span>
          </h2>
          <p className="text-slate-400 max-w-2xl mx-auto">
            One sentence. Eight comprehensive test scenarios covering happy
            paths, error states, edge cases, and security — fully generated and
            executed faster than it takes to write a single test manually.
          </p>
        </div>

        {/* Metrics */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {METRICS.map((m) => (
            <div key={m.label} className="glass-card rounded-2xl p-6 text-center">
              <div className="text-4xl font-bold gradient-text mb-1">{m.value}</div>
              <div className="text-slate-400 text-sm">{m.label}</div>
            </div>
          ))}
        </div>

        {/* Input spec */}
        <div className="glass-card rounded-2xl p-6 mb-4">
          <p className="text-xs text-slate-500 font-mono uppercase tracking-widest mb-3">Input spec</p>
          <p className="text-emerald-400 font-mono text-sm">
            &quot;Test that a user can log in with valid credentials and reach the secure dashboard&quot;
          </p>
        </div>

        {/* Terminal output */}
        <div className="glass-card rounded-2xl overflow-hidden">
          <div className="flex items-center gap-2 px-6 py-4 border-b border-white/[0.06]">
            <div className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
            <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
            <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/70" />
            <span className="ml-2 text-xs text-slate-500 font-mono">pytest output</span>
          </div>
          <div className="p-6 font-mono text-xs space-y-2.5">
            {TEST_RESULTS.map((t) => (
              <div key={t.name} className="flex items-center justify-between gap-4">
                <span className="text-slate-300 truncate">{t.name}</span>
                <div className="flex items-center gap-4 flex-shrink-0">
                  <span className="text-slate-500">{t.time}</span>
                  <span className="text-emerald-400 font-semibold">PASSED</span>
                </div>
              </div>
            ))}
            <div className="pt-4 border-t border-white/[0.06] flex items-center justify-between">
              <span className="text-emerald-400 font-semibold">8 passed in 9.47s</span>
              <span className="text-slate-500">Generated by QualiOps AI</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
