# © 2026 Wise 9 Mind Solutions LLC. All rights reserved.
"""
9MindTech AI-Assisted Test Idea Generator
Powered by Claude AI - generates real test plans from feature descriptions.
"""

import textwrap
import sys
from ai.client import get_client, CLAUDE_MODEL, extract_text, TOKENS


def generate_test_ideas_with_ai(feature_description: str) -> str:
    """Call Claude to produce a structured test plan for the given feature description."""
    client = get_client()

    prompt = f"""You are a senior QA automation engineer at a professional quality engineering firm.

A client has described the following feature:
"{feature_description}"

Generate a structured test plan with exactly these sections:
1. POSITIVE CASES - happy path scenarios
2. NEGATIVE CASES - invalid inputs and error handling
3. EDGE CASES - boundary conditions and unusual scenarios
4. API CHECKS - backend validation points
5. UI CHECKS - frontend interaction points
6. AUTOMATION PRIORITY - which tests to automate first and why

Be specific, practical, and professional. Format clearly with bullet points."""

    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=TOKENS["test_generation"],
        messages=[{"role": "user", "content": prompt}],
    )

    return extract_text(message)


def fallback_test_ideas(feature_description: str) -> dict[str, list[str]]:
    """Return a minimal static test plan when the AI client is unavailable."""
    return {
        "positive_cases": [f"Verify {feature_description} works with valid inputs."],
        "negative_cases": [f"Verify {feature_description} fails gracefully with invalid inputs."],
        "edge_cases": [f"Test boundary conditions for {feature_description}."],
        "api_checks": [f"Validate API responses for {feature_description}."],
        "ui_checks": [f"Verify UI behavior for {feature_description}."],
    }


def print_test_plan(feature_description: str) -> None:
    """Generate and print an AI-assisted test plan to stdout."""
    print("\n" + "=" * 60)
    print("  9MindTech AI-Assisted Test Plan")
    print("  Powered by Claude AI")
    print("=" * 60)
    print(f"\n  Feature: {feature_description}\n")
    print("=" * 60 + "\n")

    try:
        result = generate_test_ideas_with_ai(feature_description)
        print(result)
    except Exception as e:
        print("[AI unavailable - running fallback mode]\n")
        print(f"Error: {e}\n")
        ideas = fallback_test_ideas(feature_description)
        for category, tests in ideas.items():
            print(f"\n{category.upper()}:")
            for test in tests:
                print(textwrap.fill(f"  - {test}", width=80))

    print("\n" + "=" * 60)
    print("  Generated by 9MindTech Technologies")
    print("  wise9mind.solutions@gmail.com")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        feature = " ".join(sys.argv[1:])
    else:
        feature = input("Describe the feature to test: ").strip()
        if not feature:
            print("Please enter a feature description.")
            sys.exit(1)

    print_test_plan(feature)
